function [ h ] = drawArrow(x, y, arrow_color)

h = annotation('arrow');
set(h,'parent', gca, ... 
    'position', [x(1),y(1),x(2)-x(1),y(2)-y(1)], ...
    'HeadLength', 9, 'HeadWidth', 9, 'HeadStyle', 'vback1',...
    'Linewidth', 1.5,...
    'Color', arrow_color);

end